export const languages = {
    es: {
        "appName": "Registro de Actividad",
        "navRegister": "Registro",
        "navCalendar": "Calendario",
        "navPeople": "Personas",
        "navTexts": "Textos",
        "menuHours": "Horas",
        "menuHoursDesc": "Total de horas registradas en el mes.",
        "btnRegisterDay": "Registrar Día",
        "btnViewSummary": "Ver Resumen",
        "menuRevisits": "Revisitas",
        "menuRevisitsDesc": "Lleva un registro de tus revisitas.",
        "btnRegister": "Registrar",
        "btnViewList": "Ver Lista",
        "menuStudies": "Estudios",
        "menuStudiesDesc": "Organiza tus estudios bíblicos.",
        "menuCalendar": "Calendario",
        "menuCalendarDesc": "Visualiza tu actividad mensual.",
        "btnViewCalendar": "Ver Calendario",
        "menuFavTexts": "Textos Favoritos",
        "menuFavTextsDesc": "Guarda y organiza tus textos bíblicos.",
        "btnAdd": "Agregar",
        "btnView": "Ver",
        "formDayEntry": "Entrada del Día",
        "formDate": "Fecha de Registro",
        "formTime": "Tiempo",
        "formRevisits": "Revisitas",
        "formStudies": "Estudios",
        "btnSaveDay": "Guardar Día",
        "summaryTitle": "Resumen y Metas",
        "summaryGoal": "Establecer Meta Mensual de Horas:",
        "goalNone": "Sin meta",
        "goalHours": "{count} Horas",
        "summaryTotalHours": "Total de Horas:",
        "summaryTotalRevisits": "Total de Revisitas:",
        "summaryTotalStudies": "Total de Estudios:",
        "btnSendReport": "Enviar Informe",
        "savedEntriesTitle": "Registros Guardados Este Mes",
        "btnClearAll": "Limpiar Todos los Registros",
        "calendarTitle": "Calendario",
        "calendarDesc": "Aquí puedes ver tu calendario.",
        "peopleListTitle": "Lista de Revisitas y Estudios",
        "peopleListEmpty": "No hay personas guardadas todavía.",
        "favTextsTitle": "Textos Favoritos",
        "favTextsEmpty": "Aún no has guardado ningún texto.",
        "modalAddPersonTitle": "Agregar Detalles",
        "modalFieldName": "Nombre",
        "modalFieldNotes": "Notas / Tema de conversación",
        "btnCancel": "Cancelar",
        "btnSaveAndCount": "Guardar y Contar",
        "modalDeletePersonTitle": "Eliminar Registro",
        "modalDeletePersonDesc": "Selecciona el registro que deseas eliminar:",
        "modalAddTextTitle": "Agregar Texto Favorito",
        "modalTextRef": "Referencia del Texto (ej. Salmos 83:18)",
        "modalTextDesc": "Descripción o Notas",
        "btnSaveText": "Guardar Texto",
        "alertAttention": "Atención",
        "alertConfirm": "Confirmar",
        "btnAccept": "Aceptar",
        "toastDaySaved": "¡Día guardado con éxito!",
        "alertNameRequired": "El nombre es obligatorio.",
        "alertConfirmDeleteAll": "¿Estás seguro de que quieres borrar TODOS los registros? Esta acción no se puede deshacer.",
        "reportTitle": "Informe de Actividad - {month}",
        "reportShared": "Informe compartido con éxito.",
        "reportNotShared": "No se pudo compartir el informe.",
        "shareNotSupported": "Tu navegador no soporta la función de compartir.",
        "detailsFor": "Detalles para {date}",
        "totalTime": "Tiempo Total:",
        "totalRevisits": "Revisitas Totales:",
        "totalStudies": "Estudios Totales:",
        "confirmDeletePerson": "¿Estás seguro de que quieres eliminar a {name}?",
        "editPerson": "Editar Persona",
        "saveChanges": "Guardar Cambios",
        "alertTextRefRequired": "La referencia del texto es obligatoria.",
        "editText": "Editar Texto Favorito",
        "confirmDeleteText": "¿Estás seguro de que quieres eliminar \"{ref}\"?",
        "addRevisit": "Agregar Revisita",
        "addStudy": "Agregar Estudio"
    },
    en: {
        "appName": "Activity Log",
        "navRegister": "Log",
        "navCalendar": "Calendar",
        "navPeople": "People",
        "navTexts": "Texts",
        "menuHours": "Hours",
        "menuHoursDesc": "Total hours logged this month.",
        "btnRegisterDay": "Log Day",
        "btnViewSummary": "View Summary",
        "menuRevisits": "Return Visits",
        "menuRevisitsDesc": "Keep a record of your return visits.",
        "btnRegister": "Log",
        "btnViewList": "View List",
        "menuStudies": "Studies",
        "menuStudiesDesc": "Organize your bible studies.",
        "menuCalendar": "Calendar",
        "menuCalendarDesc": "Visualize your monthly activity.",
        "btnViewCalendar": "View Calendar",
        "menuFavTexts": "Favorite Texts",
        "menuFavTextsDesc": "Save and organize your bible texts.",
        "btnAdd": "Add",
        "btnView": "View",
        "formDayEntry": "Daily Entry",
        "formDate": "Log Date",
        "formTime": "Time",
        "formRevisits": "Return Visits",
        "formStudies": "Studies",
        "btnSaveDay": "Save Day",
        "summaryTitle": "Summary & Goals",
        "summaryGoal": "Set Monthly Hour Goal:",
        "goalNone": "No goal",
        "goalHours": "{count} Hours",
        "summaryTotalHours": "Total Hours:",
        "summaryTotalRevisits": "Total Return Visits:",
        "summaryTotalStudies": "Total Studies:",
        "btnSendReport": "Send Report",
        "savedEntriesTitle": "Entries Saved This Month",
        "btnClearAll": "Clear All Entries",
        "calendarTitle": "Calendar",
        "calendarDesc": "Here you can see your calendar.",
        "peopleListTitle": "List of Return Visits & Studies",
        "peopleListEmpty": "No people saved yet.",
        "favTextsTitle": "Favorite Texts",
        "favTextsEmpty": "You haven't saved any texts yet.",
        "modalAddPersonTitle": "Add Details",
        "modalFieldName": "Name",
        "modalFieldNotes": "Notes / Topic of conversation",
        "btnCancel": "Cancel",
        "btnSaveAndCount": "Save and Count",
        "modalDeletePersonTitle": "Delete Entry",
        "modalDeletePersonDesc": "Select the entry you want to delete:",
        "modalAddTextTitle": "Add Favorite Text",
        "modalTextRef": "Text Reference (e.g., Psalms 83:18)",
        "modalTextDesc": "Description or Notes",
        "btnSaveText": "Save Text",
        "alertAttention": "Attention",
        "alertConfirm": "Confirm",
        "btnAccept": "Accept",
        "toastDaySaved": "Day saved successfully!",
        "alertNameRequired": "Name is required.",
        "alertConfirmDeleteAll": "Are you sure you want to delete ALL entries? This action cannot be undone.",
        "reportTitle": "Activity Report - {month}",
        "reportShared": "Report shared successfully.",
        "reportNotShared": "Could not share the report.",
        "shareNotSupported": "Your browser does not support the share feature.",
        "detailsFor": "Details for {date}",
        "totalTime": "Total Time:",
        "totalRevisits": "Total Return Visits:",
        "totalStudies": "Total Studies:",
        "confirmDeletePerson": "Are you sure you want to delete {name}?",
        "editPerson": "Edit Person",
        "saveChanges": "Save Changes",
        "alertTextRefRequired": "The text reference is required.",
        "editText": "Edit Favorite Text",
        "confirmDeleteText": "Are you sure you want to delete \"{ref}\"?",
        "addRevisit": "Add Return Visit",
        "addStudy": "Add Study"
    }
};